name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Droplet
      env:
        PRIVATE_KEY: ${{ secrets.DROPLET_PRIVATE_KEY }}
        HOST: ${{ secrets.DROPLET_HOST }}
        USER: ${{ secrets.DROPLET_USER }}
      run: |
        echo "Deploying to Droplet..."
        echo "$PRIVATE_KEY" > github-deploy.pem && chmod 600 github-deploy.pem
        ssh -o StrictHostKeyChecking=no -i github-deploy.pem ${USER}@${HOST} '
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la ~

        echo "Pulling from main..."
        cd ~/seantanyurong-server
        git pull origin main

        echo "Starting/restarting application..."
        sudo systemctl restart seantanyurong-server.service
        '
